export const LOAD_WEATHER_START = 'LOAD_WEATHER_START';
export const LOAD_WEATHER_SUCCESS = 'LOAD_WEATHER_SUCCESS';
export const LOAD_WEATHER_FAILURE = 'LOAD_WEATHER_FAILURE';
export const LOAD_WEATHER_EVERY3HOURS_START = 'LOAD_WEATHER_EVERY3HOURS_START';
export const LOAD_WEATHER_EVERY3HOURS_SUCCESS = 'LOAD_WEATHER_EVERY3HOURS_SUCCESS';
export const LOAD_WEATHER_EVERY3HOURS_FAILURE = 'LOAD_WEATHER_EVERY3HOURS_FAILURE';
export const GET_THERM_UNIT = 'GET_THERM_UNIT';
